In [64]:
import numpy as np
import sys
from numpy import random

In [3]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [4]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [19]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [20]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [28]:
#The searchsorted() method is assumed to be used on sorted arrays.
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [29]:
arr = np.array([6, 8, 7, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [30]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [31]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [32]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [33]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [34]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [35]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [36]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [45]:
arr = np.array([41, 42, 43, 44])
true=arr>42
print(arr>42)
print(arr[true])

[False False  True  True]
[43 44]


In [38]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [58]:
array=np.array([1,2,3,4,5,6,7,8,9,10])

filterr=[]
for x in array:
    if x %2 ==0:
        filterr.append(True)
    else:
        filterr.append(False)

print(array[filterr])

[ 2  4  6  8 10]


In [62]:
flag=array%2==0
array[flag]

array([ 2,  4,  6,  8, 10])

In [65]:
x = random.randint(100)

print(x)

22


In [66]:
x = random.rand()

print(x)

0.3497657416196557


In [67]:
x=random.randint(100, size=(5))

print(x)

[91  5 61 23  0]


In [76]:
x = random.randint(100, size=(3, 5))

print(x)


[[82 74 22  5 11]
 [83 94 35 56 88]
 [28 66 74 88 68]]


In [73]:
x = random.rand(5)

print(x)

[0.82379087 0.43426829 0.09870789 0.63707869 0.25508509]


In [74]:
x = random.rand(3, 5)

print(x)

[[0.48799747 0.61010605 0.41814941 0.87312225 0.05146576]
 [0.09819798 0.86921535 0.76644097 0.51503678 0.16894284]
 [0.8122722  0.97376807 0.95362475 0.82892643 0.63407531]]


In [84]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
x = random.choice(array)

print(x)

4


In [85]:
x = random.choice([3, 5, 7, 9])

print(x)

3


In [86]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 7 9 7 7]
 [3 7 9 3 3]
 [7 5 7 3 9]]


Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0

In [102]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 5 5 5 7 5 7 7 5 5 7 5 5 7 5 7 7 7 7 7 3 7 5 7 7 7 7 7 5 5 5 5 7 7 7 5
 5 5 5 5 7 7 5 7 7 7 7 5 7 5 3 5 7 5 7 5 3 5 7 7 7 7 7 7 5 5 7 5 5 7 5 7 7
 7 7 7 7 7 7 3 7 7 5 5 5 5 7 5 7 7 5 7 3 7 7 5 3 7 7]


In [91]:
x = random.choice([1,2,3,4,5], p=[0.1, 0.2, 0.4, 0.2, 0.1], size=(100))
# The sum of all probability numbers should be 1.
perm=x
perm

array([3, 3, 2, 2, 4, 4, 2, 4, 3, 3, 4, 3, 3, 2, 4, 2, 2, 1, 3, 4, 1, 4,
       2, 2, 4, 2, 3, 2, 2, 3, 4, 4, 3, 1, 3, 2, 3, 4, 3, 3, 4, 3, 4, 5,
       2, 3, 5, 2, 3, 2, 2, 2, 1, 3, 2, 3, 2, 2, 4, 4, 3, 3, 3, 3, 2, 5,
       5, 2, 4, 2, 5, 3, 5, 2, 3, 3, 5, 3, 2, 1, 3, 3, 2, 3, 5, 3, 4, 3,
       4, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3])

In [101]:
np.count_nonzero(perm==3)

41

In [103]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 3 7 5 5]
 [7 7 7 5 7]
 [7 3 7 7 3]]


In [107]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)
#The shuffle() method makes changes to the original array.

[4 1 3 5 2]


In [108]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))
#The permutation() method returns a re-arranged array (and leaves the original array un-changed).

[3 4 2 1 5]
