### *Load in NumPy* (remember to pip install numpy first)

In [88]:
import numpy as np
import sys

### The Basics

In [89]:
a=np.array([1,2,3], dtype='int32')
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

# print matrix
print(a)

# get dimentions 
print("Dimention of a", a.ndim)
print("Dimention of b", b.ndim)

# get type/size
print("Type of b: ", b.dtype, "Size", b.itemsize, "bytes")
print("Type of a: ", a.dtype, "Size", a.itemsize, "bytes")

[1 2 3]
Dimention of a 1
Dimention of b 2
Type of b:  float64 Size 8 bytes
Type of a:  int32 Size 4 bytes


In [90]:
#get shape 
print(b.shape)
print(a.shape)

(2, 3)
(3,)


In [91]:
# (2,3) means 2 rows and 3 columns in b. (3,) means a vector

In [92]:
a.itemsize

4

In [93]:
#Get total size
print(a.size * a.itemsize)

#same result can be obtained by:
print(a.nbytes)

12
12


In [94]:
a.size

3

In [95]:
a.itemsize

4

### Assessing/Changing specific elements, rows, columns, etc

In [96]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [97]:
# in order to get 13 which is the 2nd row and 6th column, we will use a[row, column]
print(a[1,5])
a[1,5]

13


np.int64(13)

In [98]:
# get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [99]:
#get specific column
a[:,6]

array([ 7, 14])

In [100]:
# a[row number, starting index : ending index : step size]
a[0, 1:6:2]

array([2, 4, 6])

In [101]:
#changing element in array
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [103]:
#changing whole row 
a[0,0:-1]=0
print(a)

[[ 0  0  0  0  0  0  7]
 [ 8  9 10 11 12 20 14]]


In [104]:
#changing whole column
a[:,2]=10
print(a)

[[ 0  0 10  0  0  0  7]
 [ 8  9 10 11 12 20 14]]


In [105]:
a[:,2]=[20,40]
print(a)

[[ 0  0 20  0  0  0  7]
 [ 8  9 40 11 12 20 14]]


In [120]:
# 3-d array
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [121]:
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [122]:
d[0,1,1]

np.int64(4)

### Initializing Different Types of Arrays

In [131]:
# All 0s matrix
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [136]:
# All 1s matrix 
np.ones((3,3,3), dtype='int32' )

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [137]:
# Any other Numver
np.full((4,3),88)

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [138]:
# Any other number (full_like)
np.full_like(a,99) # or np.full(a.shape,99) does the same work

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [139]:
np.full(a.shape,99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [140]:
# Random decimal numbers
np.random.rand(4,3)

array([[0.16007197, 0.52666306, 0.71734701],
       [0.52860128, 0.92667013, 0.71090968],
       [0.94074156, 0.89961663, 0.89218808],
       [0.82462506, 0.98167691, 0.28117814]])

In [147]:
# Random Interger values
np.random.randint(50,100, size=(4,3))

array([[93, 64, 51],
       [68, 70, 73],
       [60, 98, 73],
       [52, 64, 52]], dtype=int32)

In [148]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [158]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [160]:
task=np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])

In [161]:
print(task)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [194]:
result=np.zeros((5,5))

#result[0,0:]=1
result[0]=1
result[:,0]=1
result[:,4]=1
result[4]=1
result[2,2]=9
print(result)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [196]:
result=np.ones((5,5))
print(result)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [197]:
zeros=np.zeros((3,3))

In [198]:
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [199]:
zeros[1,1]=9

In [200]:
zeros

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [202]:
result[1:-1,1:-1]=zeros

In [203]:
result

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be Careful when copying arrays 

In [206]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [207]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [208]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [209]:
a+2

array([3, 4, 5, 6])

In [210]:
a-2

array([-1,  0,  1,  2])

In [211]:
a*2

array([2, 4, 6, 8])

In [212]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [214]:
b=np.array([1,1,1,1])
a+b

array([2, 3, 4, 5])

In [215]:
# a power 2
a **2 

array([ 1,  4,  9, 16])

In [223]:
# Take the sin value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [224]:
# cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [230]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [233]:
a*b #it will give an error because both matrics are of different sizes, now we will use np.matmul(matric multiplication)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [234]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [236]:
# Find the determinant
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

### Statistics 

In [238]:
stats=np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [243]:
Min=np.min(stats, axis=1)
eachMin=np.min(stats)
print(Min)
print(eachMin)

[1 4]
1


In [244]:
np.max(stats, axis=1)

array([3, 6])

In [245]:
np.max(stats)

np.int64(6)

In [246]:
np.sum(stats)

np.int64(21)

### Reorganizing Arrays

In [248]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [249]:
before.reshape((8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [250]:
before.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Vertically Stacking vectors

In [255]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [262]:
np.vstack([[0,0,0,0],v1,v1,v2,v2,[0,0,0,0]])

array([[0, 0, 0, 0],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [0, 0, 0, 0]])

In [268]:
# Horizontal stacking vectos
h1=np.zeros([3,4]) 
h2=np.ones([3,5])
print(h1)
print(h2)

np.hstack((h1,h2))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1.]])

# Miscellaneous
### Load Data From File

In [282]:
filedata=np.genfromtxt('notepad.txt',delimiter=',')
filedata=filedata.astype('int')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advanced Indexing

In [293]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [287]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [291]:
## you can index with a list in NumPy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[2,4,6]]

array([3, 5, 7])

In [292]:
np.all(filedata > 50 , axis =0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [294]:
np.all(filedata > 50 , axis =1)

array([False, False, False])

In [295]:
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [299]:
(~((filedata>50) & (filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
# QUIZ: fetch [[11, 12],   [ 2,  8, 14, 20],    and   [ 4,  5]  from the below matrix
#             [16, 17]])                              [24, 25]
#                                                     [29, 30] 

In [308]:
quiz=np.genfromtxt('quiz.txt', delimiter=',')
quiz=quiz.astype('int')
quiz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [322]:
quiz[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [367]:
quiz[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [377]:
quiz[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])